chore: bump charts version to re-release
When enabling Immutable Releases, it was found that:

    Error: error creating GitHub release mend-renovate-ce-14.6.0: failed to
    upload release asset:
    .../mend-renovate-ce-14.6.0.tgz:
    POST
    .../assets?name=mend-renovate-ce-14.6.0.tgz:
    422 Cannot upload assets to an immutable release. []

We've disabled Immutable Releases, and so this release should run
through as expected.

[0]: https://github.com/mend/renovate-ce-ee/actions/runs/26773212037/job/78917883859